[versions]
junitVersion = '5.10.2'

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVersion" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
